name: CI-CD for E-Commerce Server

# Trigger this workflow on push events to the main branch and manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete old container if exists
        run: |
          if [ $(docker ps -q -f name=ecommerce-server) ]; then
            echo "Stopping and removing existing container"
            docker stop ecommerce-server
            docker rm ecommerce-server
          else
            echo "No existing container found"
          fi

      - name: Build Docker image
        run: docker build -t ecommerce-server:latest .

      - name: Create .env file from GitHub Secrets
        run: |
          echo "${{ secrets.PROD_ENV }}" > .env

      # - name: Run Docker container
      #   run: |
      #     docker run -d \
      #       --name ecommerce-server \
      #       -p 8000:8000 \
      #       --env-file .env \
      #       ecommerce-server:latest
