name: CI-CD for E-Commerce Server

# Trigger this workflow on push events to the main branch and manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permissions needed for the workflow
permissions:
  contents: write

# Define the jobs to be run in the workflow
jobs:
  # Deploy Job
  deploy:
    # Use a self-hosted runner for deployment
    runs-on: self-hosted

    # Steps to be executed in the Deploy job
    steps: 
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # SSH into EC2 instance and deploy the application
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/ecommerce-server
            git pull origin main
            npm install
            npm run build
            pm2 restart ecommerce-server || pm2 start npm --name "ecommerce-server" -- run start
